name: Test CDK
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      attestations: write
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - name: Instal CDK
        run: npm install -g aws-cdk
      - name: Install Hatch
        uses: pypa/hatch@install
      - name: Code Analysis
        run: hatch fmt --check
      - name: Test
        run: hatch test --cover
